Dashboard/Search/KingRichardsKnight/
basimhennawi/hackerrank pull request #2
Opened 2017-03-28 21:31 UTC by Ayman-Mohamed

2017-03-28 23:02 UTC, basimhennawi requested changes
Nice job btw! (Y)

2017-03-28 23:02 UTC, basimhennawi commented on src/Dashboard/Search/KingRichardsKnight/Solution.java
> +{
For sake of convention:
- Let's keep the opening of the brackets/braces/parenthesis in the end of the line not a new line.
- Remove unnecessary blank lines within the code.
- Keep just a blank line in the end of each file (known as EOF). (You already made it).

Please apply this in all.

2017-03-28 23:02 UTC, basimhennawi commented on src/Dashboard/Search/KingRichardsKnight/Solution.java
> +import java.io.*;
Remove unused packages import, and try to avoid importing using all (*) as much as possible.

2017-03-28 23:16 UTC, Ayman-Mohamed commented
ok, I think it's good now. 
Sometimes I keep newlines between blocks of code like a big if or for block for the sake of clarity, I think it makes the code clearer.

2017-03-29 15:54 UTC, basimhennawi approved these changes

2017-03-29 15:54 UTC, merged