Ayman
basimhennawi/hackerrank pull request #5
Opened 2017-03-30 23:54 UTC by Ayman-Mohamed

2017-03-30 23:57 UTC, basimhennawi requested changes
Keep up the good work!

2017-03-30 23:57 UTC, basimhennawi commented on src/Dashboard/Algorithms/DynamicProgramming/TheCoinChangeProblem/Solution.java
> +
Please unify the code indentation to use 4-char-spaces instead of tab.

2017-03-31 00:31 UTC, Ayman-Mohamed commented
I was wondering why the indentation was in such bad shape, I didn't realize it messed up tabs like that :)

2017-03-31 00:33 UTC, basimhennawi approved these changes

2017-03-31 00:34 UTC, merged